In [ ]:
# **Exercise 1: Test your knowledge now to write the following code.**
# data = 5649
# write a "while loop" to print data variable in reverse order

data=5649
r = 0
while(data>0):
   n=data%10
   r=r*10+n  
   data=data//10  ###floor div
print("rev",r) 

rev 9465


In [ ]:
# **Exercise 2: write a print statement to get following result.** 
# name: <any name>        roll no: <roll no>        GATE rank: <rank>       percentile: <percentile> 
name=input("name ")
rollno=input("no")
rollno=int(rollno)
gaterank=int(input("gate rank"))
percentile=int(input("percentile"))
print(name ,rollno ,gaterank ,percentile)


name tom
no123
gate rank12345
percentile77
tom 123 12345 77


In [ ]:
# **Exercise 3: Now test your understanding!

# We have a list of players as follows.
# 
# players = ['abc, 'de', 'efg', 'ijk', 'lmn', 'op', 'qq', 'rr']
# 
# **abc, lmn, qq, rr reached the semifinal of the tournament. 
# **Print the updated players list. 

players = ['abc', 'de', 'efg', 'ijk', 'lmn', 'op', 'qq', 'rr']
 
unwanted_num = {'de','efg','ijk','op'} 
wanted={'abc', 'lmn', 'qq', 'rr'}
  
players = [ele for ele in players if ele  in wanted] 
  
# printing modified list 
print("New list : ", players) 

New list :  ['abc', 'lmn', 'qq', 'rr']


In [13]:
# **Exercise 4: Write a simple program to print the first letter of your name using only asterisk '\' ( as you might have done while learning loops in 'C' language programs) **
i=1
k=1
while i!=5:
      j=1
      print("*",end='')
      
     
      while i>j:
        print(" ",end='')    #no new line
        j=j+1
      print("*",end='')
      while k!=4:
        print(" ",end='')
        k=k+1
      print("*")  
      
      i=i+1
      k=i


**   *
* *  *
*  * *
*   **


In [ ]:
# **Exercise 5: **
# 
# (i) Generate two arrays A1 and A2 of size 5 X 4 and 3 X 4 respectively using np.random()
# 
# (ii) Join them and make an array A3 of 8 X 4. Now append random numbers ranging between from 0 to 5 to make the fourth array A4 of size 10 X 10. 
# 
# (iii) Print all the arrays and their transpose ( Transpose of 'A' can be obtained by 'A.T')
import numpy as np
A1=np.random.random((5,4))
print("A1",A1)
A2=np.random.random((3,4))
print("A2",A2)
A3=np.concatenate((A1,A2),axis=0) #columwise
print("A3",A3)
A4=np.resize(A3,(10,10))
print("A4",A4)
print("a4 transpose",A4.T)

A1 [[0.58625525 0.82769949 0.12078268 0.49417794]
 [0.38417704 0.439144   0.33991565 0.88914867]
 [0.30650901 0.47371291 0.8028092  0.42947336]
 [0.82060441 0.29794053 0.72034807 0.01599313]
 [0.17341776 0.36956988 0.22000496 0.51831007]]
A2 [[0.18194427 0.47618116 0.01072638 0.84616467]
 [0.68494833 0.07362823 0.65679263 0.89452308]
 [0.3588114  0.73921793 0.27529111 0.89965895]]
A3 [[0.58625525 0.82769949 0.12078268 0.49417794]
 [0.38417704 0.439144   0.33991565 0.88914867]
 [0.30650901 0.47371291 0.8028092  0.42947336]
 [0.82060441 0.29794053 0.72034807 0.01599313]
 [0.17341776 0.36956988 0.22000496 0.51831007]
 [0.18194427 0.47618116 0.01072638 0.84616467]
 [0.68494833 0.07362823 0.65679263 0.89452308]
 [0.3588114  0.73921793 0.27529111 0.89965895]]
A4 [[0.58625525 0.82769949 0.12078268 0.49417794 0.38417704 0.439144
  0.33991565 0.88914867 0.30650901 0.47371291]
 [0.8028092  0.42947336 0.82060441 0.29794053 0.72034807 0.01599313
  0.17341776 0.36956988 0.22000496 0.51831007]
 [0.1

In [35]:
# **Exercise 6: Create two dictionaries. ** 
# 
# The first dictionary 'name' will contain first name(key) of a person and its hash value(value). 
# The Second will contain hash value(key) and mobile no(value).
# i) Add 5 entries 
# ii) Delete two entries by taking the input from user as the first name.
# ii) Add two entries by taking the input as the first name and mobile no. 
dictionary1=[
             {
                 'name':"tom",
                 'key':1
             },
             {
                 'name':"sam",
                 'key':2
             },
]

dictionary2=[
             {
                'key':1,
                'num':123
             },
             {
                 'key':1,
                 'num':456
             },
]
temp=0
while temp==0:
  length =dictionary1.__len__()
  ip=  input('To Add,delete,display enter A,D,B respectively')
  if (ip=='A'):
    name=input("Enter name")
    number=input("Enter number")
    key1=dictionary1[length-1]['key']+1
    new1={'name':name,'key':key1}
    new2={'key':key1,'num':number}
    dictionary1.append(new1)
    dictionary2.append(new2)
  elif (ip=='D'):
     name1=input("Enter name")
     i=0
     while i<length:
      if (dictionary1[i]['name']==name1):
        dictionary1.pop[i]
        dictionary2.pop[i]
        i=i+1
  elif (ip=='B'):
     i=0
     while i<length:
       print(dictionary1[i]['name'])
       print(dictionary2[i]['num'])     
       i=i+1
  else:
   print("invalid")




To Add,delete,display enter A,D,B respectivelyA
Enter nameniti
Enter number789
To Add,delete,display enter A,D,B respectivelyB
tom
123
sam
456
niti
789


KeyboardInterrupt: ignored